spring:
  redis:
    host: 192.168.1.101
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/bamboo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root