spring:
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    session:
      timeout: 1
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.techtide.web.po

mapper:
  mappers: com.techtide.web.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql